module.exports = {
  ////// CONFIGURATION TEMPLATE: uncomment desired lines to override default config.
  ////// While all lines are commented, config will not change anything.
  toolbar: {
    items: [
      "heading",
      "|",
      "fontFamily",
      "fontSize",
      "fontColor",
      "highLight",
      "|",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "subscript",
      "superscript",
      "removeFormat",
      "code",
      "link",
      "bulletedList",
      "numberedList",
      "todoList",
      "insertImage",
      "strapiMediaLib",
      "|",
      "alignment",
      "indent",
      "outdent",
      "|",
      "specialCharacters",
      "blockQuote",
      "insertTable",
      "mediaEmbed",
      "htmlEmbed",
      "codeBlock",
      "horizontalLine",
      "|",
      "fullScreen",
      "undo",
      "redo",
    ],
    shouldNotGroupWhenFull: true,
  },
  image: {
    styles: ["alignLeft", "alignCenter", "alignRight"],
    resizeOptions: [
      {
        name: "resizeImage:original",
        value: null,
        icon: "original",
      },
      {
        name: "resizeImage:50",
        value: "50",
        icon: "medium",
      },
      {
        name: "resizeImage:75",
        value: "75",
        icon: "large",
      },
    ],
    toolbar: [
      "imageStyle:alignLeft",
      "imageStyle:alignCenter",
      "imageStyle:alignRight",
      "|",
      "imageTextAlternative",
      "|",
      "resizeImage:50",
      "resizeImage:75",
      "resizeImage:original",
      "|",
      "linkImage",
    ],
  },
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
  fontColor: {
    colors: [
      { label: "textBlue", color: "#122F90" },
      { label: "success100", color: "#ECF4D8" },
      { label: "success200", color: "#D8EAB2" },
      { label: "success300", color: "#C5DF8B" },
      { label: "success400", color: "#B1D565" },
      { label: "success500", color: "#9ECA3E" },
      { label: "success600", color: "#7EA232" },
      { label: "success700", color: "#5F7925" },
      { label: "success800", color: "#3F5119" },
      { label: "success900", color: "#20280C" },
      { label: "error100", color: "#FBDAD4" },
      { label: "error200", color: "#F7B4A8" },
      { label: "error300", color: "#F38F7D" },
      { label: "error400", color: "#EF6951" },
      { label: "error500", color: "#EB4426" },
      { label: "error600", color: "#BC361E" },
      { label: "error700", color: "#8D2917" },
      { label: "error800", color: "#5E1B0F" },
      { label: "error900", color: "#2F0E08" },
      { label: "white", color: "#ffffff" },
      { label: "black", color: "#000000" },
      { label: "primary100", color: "#E5F7F8" },
      { label: "primary200", color: "#CCEFF1" },
      { label: "primary300", color: "#A1DFE5" },
      { label: "primary400", color: "#66CED6" },
      { label: "primary500", color: "#00ADBB" },
      { label: "primary600", color: "#008A96" },
      { label: "primary700", color: "#006870" },
      { label: "primary800", color: "#00454B" },
      { label: "primary900", color: "#002325" },
      { label: "zen200", color: "#9BBEFB" },
      { label: "zen300", color: "#699DFA" },
      { label: "zen400", color: "#377DF8" },
      { label: "zen500", color: "#055CF6" },
      { label: "zen600", color: "#044AC5" },
      { label: "zen700", color: "#033794" },
      { label: "zen800", color: "#022562" },
      { label: "zen900", color: "#011231" },
      { label: "greyScale100", color: "#E1E1E1" },
      { label: "greyScale200", color: "#C3C3C3" },
      { label: "greyScale300", color: "#A5A5A5" },
      { label: "greyScale400", color: "#878787" },
      { label: "greyScale500", color: "#696969" },
      { label: "greyScale600", color: "#545454" },
      { label: "greyScale700", color: "#3F3F3F" },
      { label: "greyScale800", color: "#2A2A2A" },
      { label: "greyScale900", color: "#151515" },
    ],
  },
  heading: {
    options: [
      { model: "paragraph", title: "Paragraph", class: "ck-heading_paragraph" },
      {
        model: "heading1",
        view: "h1",
        title: "Heading 1",
        class: "ck-heading_heading1",
      },
      {
        model: "heading2",
        view: "h2",
        title: "Heading 2",
        class: "ck-heading_heading2",
      },
      {
        model: "heading3",
        view: "h3",
        title: "Heading 3",
        class: "ck-heading_heading3",
      },
      {
        model: "heading4",
        view: "h4",
        title: "Heading 4",
        class: "ck-heading_heading4",
      },
    ],
  },
  highLight: {
    options: [
      {
        model: "yellowMarker",
        class: "marker-yellow",
        title: "Yellow marker",
        color: "var(--ck-highlight-marker-yellow)",
        type: "marker",
      },
      {
        model: "greenMarker",
        class: "marker-green",
        title: "Green marker",
        color: "var(--ck-highlight-marker-green)",
        type: "marker",
      },
      {
        model: "pinkMarker",
        class: "marker-pink",
        title: "Pink marker",
        color: "var(--ck-highlight-marker-pink)",
        type: "marker",
      },
      {
        model: "blueMarker",
        class: "marker-blue",
        title: "Blue marker",
        color: "var(--ck-highlight-marker-blue)",
        type: "marker",
      },
      {
        model: "redPen",
        class: "pen-red",
        title: "Red pen",
        color: "var(--ck-highlight-pen-red)",
        type: "pen",
      },
      {
        model: "greenPen",
        class: "pen-green",
        title: "Green pen",
        color: "var(--ck-highlight-pen-green)",
        type: "pen",
      },
    ],
  },
  htmlEmbed: {
    showPreviews: true,
  },
  fontFamily: {
    options: [
      "BalooChettan2-Bold",
      "BalooChettan2-ExtraBold",
      "BalooChettan2-Medium",
      "BalooChettan2-Regular",
      "BalooChettan2-SemiBold",
      "Lato-Black",
      "Lato-BlackItalic",
      "Lato-Bold",
      "Lato-BoldItalic",
      "Lato-Italic",
      "Lato-Light",
      "Lato-LightItalic",
      "Lato-Regular",
      "Lato-Thin",
      "Lato-ThinItalic",
      "Nunito-Black",
      "Nunito-BlackItalic",
      "Nunito-Bold",
      "Nunito-BoldItalic",
      "Nunito-ExtraBold",
      "Nunito-ExtraBoldItalic",
      "Nunito-ExtraLight",
      "Nunito-ExtraLightItalic",
      "Nunito-Italic",
      "Nunito-Light",
      "Nunito-LightItalic",
      "Nunito-Medium",
      "Nunito-MediumItalic",
      "Nunito-Regular",
      "Nunito-SemiBold",
      "Nunito-SemiBoldItalic",
      "NotoSans-Black",
      "NotoSans-BlackItalic",
      "NotoSans-Bold",
      "NotoSans-BoldItalic",
      "NotoSans-ExtraBold",
      "NotoSans-ExtraBoldItalic",
      "NotoSans-ExtraLight",
      "NotoSans-ExtraLightItalic",
      "NotoSans-Italic",
      "NotoSans-Light",
      "NotoSans-LightItalic",
      "NotoSans-Medium",
      "NotoSans-MediumItalic",
      "NotoSans-Regular",
      "NotoSans-SemiBold",
      "NotoSans-SemiBoldItalic",
      "NotoSans-Thin",
      "NotoSans-ThinItalic",
    ],
  },
  fontSize: {
    options: [10, 12, 14, 16, 18, 24, 28, 32, 36, 42],
    supportAllValues: true,
  },
  link: {
    defaultProtocol: "https://",
    decorators: [
      {
        mode: "manual",
        label: "Open in a new tab",
        defaultValue: true,
        attributes: {
          target: "_blank",
          rel: "noopener noreferrer",
        },
      },
      {
        mode: "manual",
        label: "Downloadable",
        attributes: {
          download: "download",
        },
      },
    ],
  },
};
